spring:
  config:
    activate:
      on-profile: "local & !prod"
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:54321/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

decorator:
  datasource:
    p6spy:
      enable-logging: ${P6SPY_ENABLE_LOGGING:true}

app:
  auth:
    cookie:
      secure: false
