spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: false
