[versions]
checkstyle = "13.4.2"
palantir-java-format = "2.80.0"
p6spy = "2.0.1"
querydsl = "5.1.0"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
spring-modulith = "2.1.1"
springdoc = "3.1.0"
spotless = "8.5.1"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
