CREATE TABLE app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR(100) NOT NULL,
  status VARCHAR(32) NOT NULL,
  CONSTRAINT ck_app_user_status CHECK (status IN ('PENDING_ONBOARDING', 'ACTIVE'))
);

CREATE TABLE user_social_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  provider VARCHAR(32) NOT NULL,
  provider_user_id VARCHAR(255) NOT NULL,
  CONSTRAINT fk_user_social_account_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
  CONSTRAINT uk_user_social_account_provider_subject UNIQUE (provider, provider_user_id),
  CONSTRAINT ck_user_social_account_provider CHECK (provider IN ('KAKAO'))
);

CREATE INDEX ix_user_social_account_user_id ON user_social_account (user_id);
